import test from'node:test';import assert from'node:assert/strict';import{readFileSync,existsSync}from'node:fs';import{webcrypto,createHash}from'node:crypto';import vm from'node:vm';import{Contract,utils}from'koilib';
const config={rpc:'https://example.test',chainId:'fixture-chain',contractId:'1CsLXtkZ78QXk1bLAyAxcyEGPDAHJELqb2'};
const manifest=JSON.parse(readFileSync('dist/collection.json'));const raw=readFileSync('dist/chain.js','utf8');
function reader(fetch){const sandbox={TextEncoder,TextDecoder,Uint8Array,BigInt,URL,AbortController,crypto:webcrypto,atob,btoa,setTimeout,clearTimeout,fetch};vm.createContext(sandbox);vm.runInContext(raw,sandbox);return sandbox.AfterlightChain;}
const A=reader(()=>{}),enc=new TextEncoder(),hash=b=>createHash('sha256').update(b).digest('hex');
function fixture({tamper=false,chainId=config.chainId,finalized=true}={}){const item=manifest.items[0],bytes=new Uint8Array(readFileSync('dist/'+item.file)),calls=[];const methods=Object.fromEntries(['get_artifact','get_chunk'].map(n=>[parseInt(hash(n).slice(0,8),16),n]));const fetch=async(url,options)=>{const req=JSON.parse(options.body);calls.push(req);let result;if(req.method==='chain.get_chain_id')result={chain_id:chainId};else{const args=A.decode(A.unb64(req.params.args));const method=methods[req.params.entry_point];if(method==='get_artifact'){const record=A.encode([[1,item.id],[2,enc.encode(item.name)],[3,enc.encode('image/webp')],[4,bytes.length],[5,A.unhex(item.sha256)],[6,enc.encode(JSON.stringify(item.metadata))],[7,Math.ceil(bytes.length/16384)],[8,Math.ceil(bytes.length/16384)],[9,finalized?1:0]]);result={result:A.b64(A.encode([[1,record]]))};}else if(method==='get_chunk'){const i=Number(args[2]||0n),b=bytes.slice(i*16384,(i+1)*16384);if(tamper&&i===0)b[0]^=1;result={result:A.b64(A.encode([[1,b]]))}}else throw Error('Unexpected read method');}return{ok:true,json:async()=>({result})}};return{reader:reader(fetch),item,bytes,calls};}
test('reconstructs an actual collection WebP from protobuf chunk responses',async()=>{const f=fixture();const r=await f.reader.reconstruct(config,1,f.item.sha256);assert.deepEqual(r.bytes,f.bytes);assert.equal(r.sha256,f.item.sha256);assert.equal(r.mime,'image/webp');assert.equal(f.calls.filter(c=>c.method==='chain.read_contract').length,1+Math.ceil(f.bytes.length/16384))});
test('rejects an incorrect network before reading image bytes',async()=>{const f=fixture({chainId:'wrong'});await assert.rejects(f.reader.reconstruct(config,1,f.item.sha256),/Wrong network/);assert.equal(f.calls.length,1)});
test('rejects tampered data even when every chunk has the correct length',async()=>{const f=fixture({tamper:true});await assert.rejects(f.reader.reconstruct(config,1,f.item.sha256),/Fingerprint mismatch/)});
test('rejects a changed on-chain commitment',async()=>{const f=fixture();await assert.rejects(f.reader.reconstruct(config,1,'00'.repeat(32)),/differs/)});
test('does not present an incomplete upload as verified art',async()=>{const f=fixture({finalized:false});await assert.rejects(f.reader.reconstruct(config,1,f.item.sha256),/not finalized/)});
test('rejects truncated protobuf fields',()=>{assert.throws(()=>A.decode(Uint8Array.from([10,20,1,2])),/Truncated/)});
test('preserves 64-bit varints without precision loss',()=>{const n=18446744073709551615n;assert.equal(A.decode(A.encode([[1,n]]))[1],n)});
test('base58 conversion matches the chain SDK address',()=>{assert.equal(A.base58(utils.decodeBase58(config.contractId)),config.contractId)});
test('all artwork matches the manifest and respects the storage cap',()=>{for(const a of manifest.items){const b=readFileSync('dist/'+a.file);assert.equal(b.length,a.bytes);assert.equal(hash(b),a.sha256);assert.ok(b.length<=200000);assert.equal(b.subarray(0,4).toString(),'RIFF');assert.equal(b.subarray(8,12).toString(),'WEBP')}});
test('the independent viewer is self-contained and matches its upload record',()=>{const b=readFileSync('dist/recovery.html');assert.ok(b.length<=200000);assert.ok(!/<script[^>]+src=|<link[^>]+href=/.test(b.toString()));const scripts=[...b.toString().matchAll(/<script>([\s\S]*?)<\/script>/g)];assert.equal(scripts.length,2);for(const script of scripts)new vm.Script(script[1]);});
test('the gallery has all locally referenced files and valid JavaScript',()=>{const html=readFileSync('dist/index.html','utf8');for(const m of html.matchAll(/(?:src|href)="([^"#]+)"/g)){if(/^(https?:|data:)/.test(m[1]))continue;assert.ok(existsSync('dist/'+m[1]),m[1])}new vm.Script(readFileSync('dist/afterhours.js','utf8'));new vm.Script(readFileSync('dist/chain.js','utf8'));const ids=new Set([...html.matchAll(/id="([^"]+)"/g)].map(m=>m[1]));for(const m of readFileSync('dist/afterhours.js','utf8').matchAll(/\$\('([^']+)'\)/g))assert.ok(ids.has(m[1]),'Missing DOM ID: '+m[1]);});
