import{System,Protobuf,authority}from'@koinos/sdk-as';import{Afterlight}from'./Afterlight';import{afterlight as p}from'./proto/afterlight';
export function main():i32{const a=System.getArguments();const c=new Afterlight();let out=new Uint8Array(0);switch(a.entry_point){case 0x4a2dbd90:out=Protobuf.encode(c.authorize(Protobuf.decode<authority.authorize_arguments>(a.args,authority.authorize_arguments.decode)),authority.authorize_result.encode);break;
case 0x82a3537f:out=Protobuf.encode(c.name(Protobuf.decode<p.name_arguments>(a.args,p.name_arguments.decode)),p.name_result.encode);break;
case 0xb76a7ca1:out=Protobuf.encode(c.symbol(Protobuf.decode<p.symbol_arguments>(a.args,p.symbol_arguments.decode)),p.symbol_result.encode);break;
case 0x70e5d7b6:out=Protobuf.encode(c.uri(Protobuf.decode<p.uri_arguments>(a.args,p.uri_arguments.decode)),p.uri_result.encode);break;
case 0x40456c8e:out=Protobuf.encode(c.token_uri(Protobuf.decode<p.token_uri_arguments>(a.args,p.token_uri_arguments.decode)),p.token_uri_result.encode);break;
case 0x4c102969:out=Protobuf.encode(c.owner(Protobuf.decode<p.owner_arguments>(a.args,p.owner_arguments.decode)),p.owner_result.encode);break;
case 0xb0da3934:out=Protobuf.encode(c.total_supply(Protobuf.decode<p.total_supply_arguments>(a.args,p.total_supply_arguments.decode)),p.total_supply_result.encode);break;
case 0x5c721497:out=Protobuf.encode(c.balance_of(Protobuf.decode<p.balance_of_arguments>(a.args,p.balance_of_arguments.decode)),p.balance_of_result.encode);break;
case 0xed61c847:out=Protobuf.encode(c.owner_of(Protobuf.decode<p.owner_of_arguments>(a.args,p.owner_of_arguments.decode)),p.owner_of_result.encode);break;
case 0x4c731020:out=Protobuf.encode(c.get_approved(Protobuf.decode<p.get_approved_arguments>(a.args,p.get_approved_arguments.decode)),p.get_approved_result.encode);break;
case 0xe7ab8ce5:out=Protobuf.encode(c.is_approved_for_all(Protobuf.decode<p.is_approved_for_all_arguments>(a.args,p.is_approved_for_all_arguments.decode)),p.is_approved_for_all_result.encode);break;
case 0x36e90cd0:out=Protobuf.encode(c.royalties(Protobuf.decode<p.royalties_arguments>(a.args,p.royalties_arguments.decode)),p.royalties_result.encode);break;
case 0xbc4fcdd4:out=Protobuf.encode(c.get_config(Protobuf.decode<p.get_config_arguments>(a.args,p.get_config_arguments.decode)),p.get_config_result.encode);break;
case 0xfcf7a68f:out=Protobuf.encode(c.get_metadata(Protobuf.decode<p.get_metadata_arguments>(a.args,p.get_metadata_arguments.decode)),p.get_metadata_result.encode);break;
case 0x8c0c0900:out=Protobuf.encode(c.get_listing(Protobuf.decode<p.get_listing_arguments>(a.args,p.get_listing_arguments.decode)),p.get_listing_result.encode);break;
case 0x7d5b5ed7:out=Protobuf.encode(c.get_tokens(Protobuf.decode<p.get_tokens_arguments>(a.args,p.get_tokens_arguments.decode)),p.get_tokens_result.encode);break;
case 0x470ebe82:out=Protobuf.encode(c.initialize(Protobuf.decode<p.initialize_arguments>(a.args,p.initialize_arguments.decode)),p.initialize_result.encode);break;
case 0xdc6f17bb:out=Protobuf.encode(c.mint(Protobuf.decode<p.mint_arguments>(a.args,p.mint_arguments.decode)),p.mint_result.encode);break;
case 0x49c09520:out=Protobuf.encode(c.open_sales(Protobuf.decode<p.open_sales_arguments>(a.args,p.open_sales_arguments.decode)),p.open_sales_result.encode);break;
case 0x35fbb717:out=Protobuf.encode(c.set_paused(Protobuf.decode<p.set_paused_arguments>(a.args,p.set_paused_arguments.decode)),p.set_paused_result.encode);break;
case 0x27f576ca:out=Protobuf.encode(c.transfer(Protobuf.decode<p.transfer_arguments>(a.args,p.transfer_arguments.decode)),p.transfer_result.encode);break;
case 0x74e21680:out=Protobuf.encode(c.approve(Protobuf.decode<p.approve_arguments>(a.args,p.approve_arguments.decode)),p.approve_result.encode);break;
case 0x20442216:out=Protobuf.encode(c.set_approval_for_all(Protobuf.decode<p.set_approval_for_all_arguments>(a.args,p.set_approval_for_all_arguments.decode)),p.set_approval_for_all_result.encode);break;
case 0xc827d2d7:out=Protobuf.encode(c.list_token(Protobuf.decode<p.list_token_arguments>(a.args,p.list_token_arguments.decode)),p.list_token_result.encode);break;
case 0x5079c71c:out=Protobuf.encode(c.cancel_listing(Protobuf.decode<p.cancel_listing_arguments>(a.args,p.cancel_listing_arguments.decode)),p.cancel_listing_result.encode);break;
case 0xe8197b20:out=Protobuf.encode(c.buy(Protobuf.decode<p.buy_arguments>(a.args,p.buy_arguments.decode)),p.buy_result.encode);break;default:System.exit(1);return 1;}System.exit(0,out);return 0;}main();
